import React, { useState, useMemo, useEffect } from 'react';
import {
  INITIAL_ENTITY_INVENTORY,
  INITIAL_NOT_REPORTED_UNITS,
  INITIAL_INCOMPLETE_UNITS,
} from './data/inventarioData';
import { calculateNationalSummary } from './utils/calculations';
import { formatDateTime } from './utils/formatters';
import { CaptureTarget } from './types';
import { Header } from './components/Header';
import { FilterBar } from './components/FilterBar';
import { SummaryCards } from './components/SummaryCards';
import { InventoryChart } from './components/InventoryChart';
import { InventoryTable } from './components/InventoryTable';
import { NotReportedTable } from './components/NotReportedTable';
import { IncompleteTable } from './components/IncompleteTable';
import { CaptureModal } from './components/CaptureModal';
import {
  CheckCircle,
  FileSpreadsheet,
  BarChart3,
  AlertOctagon,
  AlertTriangle,
  ShieldCheck,
} from 'lucide-react';

export default function App() {
  // State for inventory datasets (designed for seamless API replacement)
  const [entitiesData, setEntitiesData] = useState(INITIAL_ENTITY_INVENTORY);
  const [notReportedUnits, setNotReportedUnits] = useState(INITIAL_NOT_REPORTED_UNITS);
  const [incompleteUnits, setIncompleteUnits] = useState(INITIAL_INCOMPLETE_UNITS);
  const [isDataLoading, setIsDataLoading] = useState(true);

  // Filter state
  const [selectedEntity, setSelectedEntity] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState<string>('');

  // Active view section
  const [activeSection, setActiveSection] = useState<string>('inventory');

  // Dynamic timestamp
  const [lastUpdatedText, setLastUpdatedText] = useState<string>('');

  // Capture modal state
  const [isCaptureModalOpen, setIsCaptureModalOpen] = useState(false);
  const [captureTarget, setCaptureTarget] = useState<CaptureTarget>('full');

  // Toast notification state
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  // Initialize dynamic timestamp and load report data generated by the Python script
  useEffect(() => {
    setLastUpdatedText(formatDateTime(new Date()));

    const loadReportData = async () => {
      try {
        const response = await fetch('./reporte-inventario-data.json');
        if (!response.ok) {
          throw new Error(`No se pudo cargar el archivo de datos: ${response.status}`);
        }

        const data = await response.json();

        if (Array.isArray(data.entities) && data.entities.length > 0) {
          setEntitiesData(data.entities);
        }
        if (Array.isArray(data.notReported)) {
          setNotReportedUnits(data.notReported);
        }
        if (Array.isArray(data.incomplete)) {
          setIncompleteUnits(data.incomplete);
        }
      } catch (error) {
        console.warn('Usando datos locales del frontend porque no existe la data generada por Python.', error);
      } finally {
        setIsDataLoading(false);
      }
    };

    void loadReportData();
  }, []);

  // Show temporary toast
  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Unique list of all 32 entities
  const allEntitiesList = useMemo(() => {
    return Array.from(new Set(entitiesData.map((e) => e.entidad))).sort((a, b) =>
      a.localeCompare(b, 'es')
    );
  }, [entitiesData]);

  // Filtered entity inventory data
  const filteredEntities = useMemo(() => {
    return entitiesData.filter((item) => {
      if (selectedEntity && item.entidad !== selectedEntity) {
        return false;
      }
      if (searchTerm.trim() !== '') {
        const term = searchTerm.toLowerCase();
        const matchEntity = item.entidad.toLowerCase().includes(term);
        if (!matchEntity) return false;
      }
      return true;
    });
  }, [entitiesData, selectedEntity, searchTerm]);

  // Dynamic Executive Summary calculated from current view
  const executiveSummary = useMemo(() => {
    return calculateNationalSummary(filteredEntities);
  }, [filteredEntities]);

  // Print Handler
  const handlePrint = () => {
    window.print();
  };

  // Open Capture Dialog
  const handleOpenCapture = () => {
    const targetBySection: Record<string, CaptureTarget> = {
      inventory: 'inventory',
      'not-reported': 'not-reported',
      incomplete: 'incomplete',
      chart: 'chart',
    };

    setCaptureTarget(targetBySection[activeSection] ?? 'full');
    setIsCaptureModalOpen(true);
  };

  return (
    <div className="min-h-screen bg-[#F3F4F6] text-gray-900 flex flex-col antialiased">
      {/* Institutional Top Header */}
      <Header
        lastUpdatedText={lastUpdatedText}
        onPrint={handlePrint}
        onOpenCapture={handleOpenCapture}
      />

      {/* Sub-header Navigation Bar for Meetings & Presentations */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-30 shadow-xs print:hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between overflow-x-auto py-2 gap-2 text-xs no-scrollbar">
            <div className="flex items-center gap-1 sm:gap-2">
              <a
                href="#capture-inventory"
                onClick={() => setActiveSection('inventory')}
                className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md font-medium transition-colors whitespace-nowrap ${
                  activeSection === 'inventory'
                    ? 'bg-[#10312B] text-white'
                    : 'text-gray-600 hover:text-[#10312B] hover:bg-gray-100'
                }`}
              >
                <FileSpreadsheet className="w-3.5 h-3.5" />
                <span>Inventario por entidad federativa</span>
              </a>

              <a
                href="#section-no-reportaron"
                onClick={() => setActiveSection('not-reported')}
                className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md font-medium transition-colors whitespace-nowrap ${
                  activeSection === 'not-reported'
                    ? 'bg-rose-600 text-white'
                    : 'text-gray-600 hover:text-rose-700 hover:bg-rose-50'
                }`}
              >
                <AlertOctagon className="w-3.5 h-3.5" />
                <span>CLUES que NO reportaron ({notReportedUnits.length})</span>
              </a>

              <a
                href="#section-clues-incompletos"
                onClick={() => setActiveSection('incomplete')}
                className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md font-medium transition-colors whitespace-nowrap ${
                  activeSection === 'incomplete'
                    ? 'bg-amber-600 text-white'
                    : 'text-gray-600 hover:text-amber-800 hover:bg-amber-50'
                }`}
              >
                <AlertTriangle className="w-3.5 h-3.5" />
                <span>CLUES incompletos ({incompleteUnits.length})</span>
              </a>

              <a
                href="#capture-chart"
                onClick={() => setActiveSection('chart')}
                className={`inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md font-medium transition-colors whitespace-nowrap ${
                  activeSection === 'chart'
                    ? 'bg-[#691C32] text-white'
                    : 'text-gray-600 hover:text-[#10312B] hover:bg-gray-100'
                }`}
              >
                <BarChart3 className="w-3.5 h-3.5" />
                <span>Gráfica de avance</span>
              </a>
            </div>

          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <main
        id="capture-full-report"
        className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-5 sm:py-6 space-y-6 bg-transparent"
      >
        {/* Printable Official Banner Header (Only Visible When Printing) */}
        <div className="hidden print:block border-b-2 border-[#10312B] pb-3 mb-4">
          <div className="flex justify-between items-start">
            <div>
              <div className="text-xs uppercase font-bold text-gray-600">
                Gobierno de México · Sistema Nacional de Salud
              </div>
              <h1 className="text-xl font-bold text-black mt-0.5">
                Reporte de Inventario de Unidades Médicas
              </h1>
              <p className="text-xs text-gray-600">
                Inventario consolidado por entidad federativa · Medicamentos y Material de Curación
              </p>
            </div>
            <div className="text-right text-xs text-gray-600">
              <div>Fecha de reporte: <strong>{lastUpdatedText}</strong></div>
              <div>Entidades evaluadas: <strong>32</strong></div>
            </div>
          </div>
        </div>

        {/* Global Filter Bar */}
        <FilterBar
          selectedEntity={selectedEntity}
          onSelectEntity={setSelectedEntity}
          searchTerm={searchTerm}
          onSearchChange={setSearchTerm}
          entitiesList={allEntitiesList}
          totalMatchesCount={filteredEntities.length}
        />

        {isDataLoading && (
          <div className="bg-white border border-gray-200 rounded-lg px-4 py-3 text-xs text-gray-500 shadow-xs">
            Cargando datos reales del reporte generado por el script...
          </div>
        )}

        {activeSection === 'chart' ? (
          <InventoryChart
            data={filteredEntities}
            selectedEntity={selectedEntity}
            onSelectEntity={setSelectedEntity}
          />
        ) : (
          <>
            {activeSection === 'inventory' && (
              <InventoryTable
                data={filteredEntities}
                selectedEntity={selectedEntity}
                onSelectEntity={setSelectedEntity}
                notReportedCount={notReportedUnits.length}
              />
            )}

            {activeSection === 'not-reported' && (
              <div className="grid grid-cols-1 gap-6">
                <NotReportedTable
                  units={notReportedUnits}
                  selectedEntity={selectedEntity}
                  onSelectEntity={setSelectedEntity}
                />
              </div>
            )}

            {activeSection === 'incomplete' && (
              <div className="grid grid-cols-1 gap-6">
                <IncompleteTable
                  units={incompleteUnits}
                  selectedEntity={selectedEntity}
                  onSelectEntity={setSelectedEntity}
                />
              </div>
            )}
          </>
        )}

        {/* Institutional Document Footer */}
        <footer className="pt-6 pb-4 border-t border-gray-200 text-xs text-gray-500 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-[#10312B]" />
            <span className="font-medium text-gray-700">
              Sistema de Reporte de Inventario de Unidades Médicas
            </span>
            <span className="text-gray-400">·</span>
            <span>Versión Institucional 2026.1</span>
          </div>

          <div className="flex items-center gap-4 text-gray-400 text-[11px]">
            <span>Catálogos: 010 (Medicamentos), 040 (Especialidad), 060 (Curación)</span>
            <span>·</span>
            <span>Confidencial para uso institucional</span>
          </div>
        </footer>
      </main>

      {/* Capture High-Resolution PNG Modal */}
      <CaptureModal
        isOpen={isCaptureModalOpen}
        onClose={() => setIsCaptureModalOpen(false)}
        target={captureTarget}
        onChangeTarget={setCaptureTarget}
      />

      {/* Floating Toast Notification */}
      {toastMessage && (
        <div
          className="fixed bottom-4 right-4 z-50 bg-[#10312B] text-white px-4 py-2.5 rounded-md shadow-lg border border-[#D4C19C]/30 text-xs font-medium flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2 duration-200"
          role="status"
        >
          <CheckCircle className="w-4 h-4 text-[#D4C19C]" />
          <span>{toastMessage}</span>
        </div>
      )}
    </div>
  );
}
